json.extract! dodone,
              :id,
              :dodoable_id,
              :day_id,
              :started_at,
              :finished_at,
              :fields,
              :created_at,
              :updated_at,
              :scheduled_to,
              :status,
              :being_tracked?,
              :finished?,
              :started?,
              :statusable?
