json.extract! dodoable,
              :created_at,
              :dodone_today?,
              :executor,
              :fields,
              :id,
              :last_dodone_day_id,
              :name,
              :nature,
              :slug,
              :trigger,
              :updated_at,
              :user_id
